config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'users#dashboard', as: :dashboard
  get '/developers', to: 'pages#developers', as: :developers
  resources :projects do
    resources :chatrooms, only: :create
    resources :applications, only: [:new, :create]
    resources :reviews, only: [:new, :create]
    member do
      post :favorite
      post :unfavorite
    end
    resources :favorites, only: [:create] do
      collection do
        delete '/', action: :destroy
      end
    end
  end

  resources :applications, only: [] do
    get '/assess', to: 'applications#assess'
    patch '/', to: 'applications#respond'
  end

  resources :users, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    get '/my_skills', to: 'users#my_skills', as: :my_skills
    resources :my_skills, only:[:create]
    get '/my_languages', to: 'users#my_languages', as: :my_languages
    resources :my_languages, only:[:create]
  end
  resources :organizations, only: [:new, :create]
  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :my_skills, dependent: :destroy
  has_many :skills, through: :my_skills
  has_many :my_languages, dependent: :destroy
  has_many :languages, through: :my_languages
  has_many :my_badges, dependent: :destroy
  has_many :badges, through: :my_badges
  has_many :reviews, dependent: :destroy
  has_many :applications, dependent: :destroy
  has_many :projects, through: :applications
  enum user_type: [:volunteer, :organization]
  has_one :organization
  has_one_attached :photo, dependent: :destroy
  has_many :chatrooms
  has_many :recipient_chatrooms, class_name: "Chatroom", foreign_key: :recipient_id
  has_many :messages, through: :chatrooms
  has_many :rec_messages, through: :recipient_chatrooms, source: :messages
  acts_as_favoritor
  # include PgSearch::Model
  # pg_search_scope :search_by_name,
  #   against: [:first_name, :last_name],
  #   using: {
  #     tsearch: { prefix: true }
  #   }

  def all_messages
    messages + rec_messages
  end

  def all_chatrooms
    chatrooms + recipient_chatrooms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = Review.all
    if @user.organization?
      @organization = @user.organization
      @projects = @organization.projects
    else
      @projects = @user.projects
    end
  end

  # def edit
  #   @user = User.find(params[:id])

  # end

  # def update
  #   @user = User.find(params[:id])
  #   @user.update(user_params)
  #   redirect_to @user
  # end

  def dashboard
    @user = current_user
    @all_projects = Project.all
    @my_skill = MySkill.new
    @skills = Skill.all
    @languages = Language.all
    @my_language = MyLanguage.new
    if @user.organization?
      @organization = @user.organization
      @projects = @organization.projects
      arr = []
      @projects.each { |e| arr << e.id }
      @applications = Application.all.select { |application| arr.include?(application.project_id) } # Be careful, if there is app, it will return empty array, not nil!!!
    else
      @projects = @user.projects
      @applications = @user.applications
    end
  end

  private

  # def user_params
  #   params.require(:user).permit(:photo)
  # end
end

app/views/users/_organization.html.erb
<div class="profile-main-container">
  <div class="flex-box">
    <div class="profile-bar">
      <div class="flex-item">
        <%= cl_image_tag @user.photo.key, class: "profile-bar-photo" %>
        <div class="profile-header">
          <h2><%= @organization.name %></h2>
          <p><%= @user.user_type %></p>
          <div class="d-flex justify-content-center align-items-center">
            <% Review.where("organization_id = ? AND author_id != ?", @organization.id, @organization.id).average(:rating)&.to_i&.times do %>
              <span class="full-star">★</span>
            <% end %>
            <span class="rev-count">(<%= Review.where("organization_id = ? AND author_id != ?", @organization.id, @organization.id).count %>)</span>
          </div>
          <div class="container-badges">
            <% @user.my_badges.each do |my_badge| %>
              <% if Badge.find(my_badge.badge_id).name == "Reviewer" %>
                <div id="reviewer">
                  <%= image_tag "badges/reviewer.png" %>
                  <p id="reviewer-js"> Reviewer </p>
                </div>
              <% end %>
              <% if Badge.find(my_badge.badge_id).name == "Experienced Host" %>
                <div id="experienced">
                  <%= image_tag "badges/experienced.png" %>
                  <p id="experienced-js"> Experienced Host</p>
                </div>
              <% end %>
              <% if Badge.find(my_badge.badge_id).name == "Top Rated" %>
                <div id="top_rated">
                  <%= image_tag "badges/top_rated.png" if Badge.find(my_badge.badge_id).name == "Top Rated" %>
                  <p id="top_rated-js"> Top Rated </p>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
        <div class="profile-bar-content">
          <p><i class="fas fa-map-marker-alt"></i> <%= @user.address.upcase %></p>
          <h3>About us</h3>
          <p><%= @user.description %></p>
          <h3>What do we offer</h3>
          <p><i class="fas fa-check"></i> Acomodation in a separated room</p>
          <p><i class="fas fa-check"></i> Breakfast</p>
          <p><i class="fas fa-check"></i> Pet friendly</p>
          <p><i class="fas fa-check"></i> Parking lot</p>
          <p><i class="fas fa-check"></i> Laguage and culture exchange</p>
          <h4>Languages <i class="far fa-comment-dots"></i></h4>
          <p>English</p>
          <p>Spanish</p>
          <p>French</p>
        </div>
        <div id="accept-volunteers">
          <%= image_tag "laptop.png", alt: "laptop" %>
          <p>This host accept remote volunteers</p>
        </div>

    </div>
    <div class="profile-container">
      <div class="header">
        <h3>Projects</h3>
      </div>
      <div class="card-container">
        <% @projects.each do |project| %>
          <div class="small-cards">
            <%= link_to project_path(project) do %>
              <% if project.photos.attached? %>
                <% cl_image_tag project.photos.first.key %>
              <% else %>
                <% image_tag("project_default_background.jpg") %>
              <% end %>
            <% end %>
              <div class="project-info">
                <h2><%= project.title %></h2>
                <p><%= project.description %></p>
                <%= link_to 'See project', project_path(project) %>
              </div>
          </div>
        <% end %>
      </div>
      <div class="header mt-3">
        <h3>Volunteers Feedback</h3>
      </div>
        <div class="reviews">
          <% @organization.reviews.each do |review| %>
            <% reviewer = User.find(review.author_id) %>
            <% if reviewer.volunteer? %>
              <div class="profile-review-card">
                <div class="review-info">
                  <% if reviewer.photo.attached? %>
                    <%= cl_image_tag reviewer.photo.key, class: 'avatar-large' %>
                    <!-- <p> <%#= reviewer.organization? ?  reviewer.organization.name : "#{reviewer.first_name.capitalize}" %> </p> -->
                  <% else %>
                    <%= image_tag "default-avt.png", class: 'avatar-large' %>
                  <% end %>
                  <div class="rating-stars">
                    <% review.rating.times do %>
                      <i class="fas fa-star"></i>
                    <% end %>
                  </div>
                </div>
                <div class="rev-content">
                  <em>"<%= review.content.capitalize %>"</em>
                </div>
                <%= link_to reviewer.organization? ?  reviewer.organization.name : "#{reviewer.first_name.capitalize}", user_path(reviewer) %>
              </div>
            <% end %>
          <% end %>
            <hr>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_volunteer.html.erb
<div class="profile-main-container">
  <div class="flex-box">
    <div class="profile-bar">
      <div class="flex-item">
        <%= cl_image_tag @user.photo.key, class: "profile-bar-photo" %>
        <div class="profile-header">
          <h2><%= "#{@user.first_name.capitalize} #{@user.last_name.capitalize}" %></h2>
          <p><%= @user.user_type %></p>
          <div class="d-flex justify-content-center align-items-center">
            <% Review.where("user_id = ? AND author_id != ?", @user.id, @user.id).average(:rating)&.to_i&.times do %>
              <span class="full-star">★</span>
            <% end %>
            <% if Review.where("user_id = ? AND author_id != ?", @user.id, @user.id).count > 0 %>
              <span class="rev-count">(<%= Review.where("user_id = ? AND author_id != ?", @user.id, @user.id).count %>)</span>
            <% end %>
          </div>
          <div class="container-badges">
            <% @user.my_badges.each do |my_badge| %>
              <% if Badge.find(my_badge.badge_id).name == "Reviewer" %>
                <div id="reviewer">
                  <%= image_tag "badges/reviewer.png" %>
                  <p id="reviewer-js"> Reviewer </p>
                </div>
              <% end %>
              <% if Badge.find(my_badge.badge_id).name == "Experienced Host" %>
                <div id="experienced">
                  <%= image_tag "badges/experienced.png" %>
                  <p id="experienced-js"> Experienced Host</p>
                </div>
              <% end %>
              <% if Badge.find(my_badge.badge_id).name == "Top Rated" %>
                <div id="top_rated">
                  <%= image_tag "badges/top_rated.png" if Badge.find(my_badge.badge_id).name == "Top Rated" %>
                  <p id="top_rated-js"> Top Rated </p>
                </div>
              <% end %>
            <% end %>
          </div>
          <% #@organization.reviews.each %>
        </div>
      </div>
        <div class="profile-bar-content">
          <p><i class="fas fa-map-marker-alt"></i> <%= @user.address.upcase %></p>
          <h3>About me</h3>
          <p><%= @user.description %></p>
          <div class="mb-3">
            <% if @user.linkedin.present? || @user.github.present? %>
              <h6> Check me out on: </h6>
            <% end %>
            <% if @user.linkedin.present? %>
              <%= link_to @user.linkedin do %>
                <i class="fab fa-linkedin"></i>
              <% end %>
            <% end %>
            <% if @user.github.present? %>
              <%= link_to "https://#{@user.github }" do %>
                <i class="fab fa-github-square"></i>
              <% end %>
            <% end %>
          </div>

          <h3>My Skills <%= image_tag "laptop.png", alt: "laptop" %> </h3>
          <% @user.skills.each do |skill| %>
            <p><i class="fas fa-check"></i> <%= skill.name %></p>
          <% end %>


          <% if @user.languages.length > 0 %>
            <h4>Languages I speak <i class="far fa-comment-dots"></i></h4>
            <% @user.languages.each do |l| %>
              <p><%= l.name %></p>
            <% end %>
          <% end %>
        </div>

    </div>
    <div class="profile-container">
      <div class="header">
        <h3>Projects I worked</h3>
      </div>
      <div class="card-container">
        <% if @user.projects.blank? %>
        <p><%= "#{@user.first_name.capitalize}" %> haven't worked in any project yet.</p>
        <% else %>
        <% @projects.each do |project| %>
          <div class="small-cards">
            <%= link_to project_path(project) do %>
              <% if project.photos.attached? %>
                <% cl_image_tag project.photos.first.key %>
              <% else %>
                <% image_tag("project_default_background.jpg") %>
              <% end %>
            <% end %>
              <div class="project-info">
                <h2><%= project.title %></h2>
                <p><%= project.description %></p>
                <%= link_to 'See project', project_path(project) %>
              </div>
          </div>
        <% end %>
        <% end %>
      </div>
      <div class="header mt-3">
        <h3>Volunteers Feedback</h3>
      </div>
        <div class="reviews">
          <% @user.reviews.each do |review| %>
              <% reviewer = User.find(review.author_id) %>
              <% if reviewer.organization? %>
                <div class="profile-review-card">
                  <div class="review-info">
                    <% if reviewer.photo.attached? %>
                      <%= cl_image_tag reviewer.photo.key, class: 'avatar-large' %>
                      <!-- <p> <%#= reviewer.organization? ?  reviewer.organization.name : "#{reviewer.first_name.capitalize}" %> </p> -->
                    <% else %>
                      <%= image_tag "default-avt.png", class: 'avatar-large' %>
                    <% end %>
                    <div class="rating-stars">
                      <% review.rating.times do %>
                        <i class="fas fa-star"></i>
                      <% end %>
                    </div>
                  </div>
                  <div class="rev-content">
                    <em>"<%= review.content.capitalize %>"</em>
                  </div>
                  <%= link_to reviewer.organization? ?  reviewer.organization.name : "#{reviewer.first_name.capitalize}", user_path(reviewer) %>
                </div>
              <% end %>
            <% end %>
            <hr>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/users/dashboard.html.erb
<%# link_to 'My Profile', user_path(current_user)  %>
<div class="container-dashboard">
  <div class="hold">
    <div class="card-dashboard">
      <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key %>
      <% else %>
        <%= image_tag "default-avt.png" %>
      <% end %>
      <% if @user.organization? %>
        <h4> <%= @user.organization.name %> </h4>
        <div class="container-badges">
          <% @user.my_badges.each do |my_badge| %>
            <% if Badge.find(my_badge.badge_id).name == "Reviewer" %>
              <div id="reviewer">
                <%= image_tag "badges/reviewer.png" %>
                <p id="reviewer-js"> Reviewer </p>
              </div>
            <% end %>
            <% if Badge.find(my_badge.badge_id).name == "Experienced Host" %>
              <div id="experienced">
                <%= image_tag "badges/experienced.png" %>
                <p id="experienced-js"> Experienced Host</p>
              </div>
            <% end %>
            <% if Badge.find(my_badge.badge_id).name == "Top Rated" %>
              <div id="top_rated">
                <%= image_tag "badges/top_rated.png" if Badge.find(my_badge.badge_id).name == "Top Rated" %>
                <p id="top_rated-js"> Top Rated </p>
              </div>
            <% end %>
          <% end %>
        </div>
        
      <% else %>
        <h4> <%= "#{@user.first_name.capitalize} #{@user.last_name.capitalize}" %> </h4>
        <div class="container-badges">
          <% @user.my_badges.each do |my_badge| %>
            <% if Badge.find(my_badge.badge_id).name == "Reviewer" %>
              <div id="reviewer">
                <%= image_tag "badges/reviewer.png" %>
                <p id="reviewer-js"> Reviewer </p>
              </div>
            <% end %>
            <% if Badge.find(my_badge.badge_id).name == "Experienced Host" %>
              <div id="experienced">
                <%= image_tag "badges/experienced.png" %>
                <p id="experienced-js"> Experienced Host</p>
              </div>
            <% end %>
            <% if Badge.find(my_badge.badge_id).name == "Top Rated" %>
              <div id="top_rated">
                <%= image_tag "badges/top_rated.png" if Badge.find(my_badge.badge_id).name == "Top Rated" %>
                <p id="top_rated-js"> Top Rated </p>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class="container-current_skills">
          <% @user.my_skills.each do |my_skill| %>
            <div class="btn main-btn btn-skill"> <%= my_skill.skill.name %> </div>
          <% end %>
        </div>
        <div class="container-current_languages">
          <% @user.my_languages.each do |my_language| %>
            <div class="btn main-btn btn-language"> <%= my_language.language.name %> </div>
          <% end %>
        </div>
      <% end %>
      <% if @user.organization? %>
        <%= link_to 'Create a Project', new_project_path %>
      <% else %>
        <%= link_to user_my_skills_path(@user), :id => "add-skill" do  %>
          <div class="capsule"><p>Add Skills to Your Profile<p> <i class="fas fa-plus" ></i> </div>
        <% end %>
        <div id="popup-skills">
          <div class="container-skills">
            <% (@skills - @user.skills).each do |skill| %>
              <%= simple_form_for [current_user, @my_skill], :class => "skill" do |f| %>
                <%= hidden_field_tag("[skill]", "#{skill.id}") %>
                <%= f.submit "#{skill.name}", class: "btn main-btn btn-skill" %>
              <% end %>
            <% end %>
          </div>
          <%= link_to 'Done', dashboard_path, :class => "btn main-btn close-section" %>
        </div>
        <%= link_to user_my_languages_path(@user), :id => "add-language" do  %>
          <div class="capsule"><p>Add Languages to Your Profile<p> <i class="fas fa-plus" ></i> </div>
        <% end %>
        <div id="popup-languages">
          <div class="container-languages">
            <% (@languages - @user.languages).each do |language| %>
              <%= simple_form_for [current_user, @my_language], :class => "language" do |f| %>
                <%= hidden_field_tag("[language]", "#{language.id}") %>
                <%= f.submit "#{language.name}", class: "btn main-btn btn-language" %>
              <% end %>
            <% end %>
          </div>
          <%= link_to 'Done', dashboard_path, :class => "btn main-btn close-section" %>
        </div>
      <% end %>
      <div class="saved-items">
        <h4>Saved <i class="far fa-bookmark"></i></h4>
        <% current_user.all_favorited.each do |i| %>
          <%=link_to "##{i.title}", project_path(i) %>
        <% end %>
      </div>
    </div>
    <div class="applications-projects"> 
      <div class="applications">
        <h3>Applications</h3>
        <hr>
        <h4>Open</h4>
        <% @applications.select { |e| e.open? }.each do |application| %>
          <div class="accordion" id="accordionExample">
            <div class="card">
              <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                  <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#a<%= application.id %>" aria-expanded="false" aria-controls="a<%= application.id %>">
                    <% if current_user.organization? %>
                      <p><%= "#{application.created_at.strftime("%m/%d/%Y")} / #{application.user.first_name} #{application.user.last_name} - #{application.project.title}" %> </p>
                    <% else %>
                      <p><%= "#{application.created_at.strftime("%m/%d/%Y")} - #{application.project.title}" %> </p>
                    <% end %>
                  </button>
                </h5>
              </div>
              <div id="a<%= application.id %>" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample" >
                <div class="card-body">
                  <div>

                    <h5>Project: <%= link_to application.project.title, project_path(application.project), class: "h5-links" %></h5>
                    <div class="description">
                      <p><%= application.project.description %></p>
                    </div>
                    <div class="mt-4">
                      <h5>Applicant: <%= link_to "#{application.user.first_name}  #{application.user.last_name}", user_path(application.user), class: "h5-links" %></h5>
                      <div class="letter">
                        <p><%= application.motivation_letter %></p>
                      </div>
                    </div>
                    <div class="mt-4">
                      <% if application.user.linkedin.present? || application.user.github.present? %>
                        <h6> Check me out on: </h6>
                      <% end %>
                      <% if application.user.linkedin.present? %>
                        <%= link_to application.user.linkedin do %>
                          <i class="fab fa-linkedin"></i>
                        <% end %>
                      <% end %>


                  
                      <% if application.user.github.present? %>
                        <%= link_to "https://#{application.user.github }" do %>
                          <i class="fab fa-github-square"></i>
                        <% end %>
                      <% end %>
                    </div>
                    <p><%= cl_image_tag application.resume.key if  application.resume %></p>
                    <div class="accept-decline">
                      <% if current_user.organization? %>

                        <% chatroom = Chatroom.where(user: current_user, recipient: application.user).or(Chatroom.where(user: application.user, recipient: current_user)).first
%>
                        <% if chatroom %>
                          <%= link_to "Contact", chatroom_path(chatroom), class: "btn-transparent"  %>
                        <% else %>
                          <%= link_to 'Contact', project_chatrooms_path(application.project), method: :post, class: "btn-transparent"  %>
                        <% end %>

                        <%= simple_form_for (application), :method => :patch do |f| %>
                          <%= hidden_field_tag "application[status]", "accepted" %>
                          <%= f.submit "Accept", class: "btn-light-green" %>
                        <% end %>






                        <%= simple_form_for (application), :method => :patch do |f| %>
                          <%= hidden_field_tag("application[status]", "declined") %>
                          <%= f.submit "Decline", class: "btn-coral" %>
                        <% end %>




                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
        <p><em><%= "Open applications will be displayed here" unless @applications.select { |e| e.open? }.first %></em></p>
        <h4>Approved</h4>
        <% @applications.select { |e| e.accepted? && Date.today < e.project.end_date }.each do |application| %>
          <div>
            <% if current_user.organization? %>
              <p><%= "#{application.created_at.strftime("%m/%d/%Y")} / #{application.user.first_name} #{application.user.last_name} - #{application.project.title}" %> </p>
            <% else %>
              <p><%= "#{application.created_at.strftime("%m/%d/%Y")} - #{application.project.title}" %> </p>
            <% end %>
          </div>
        <% end %>
        <p><em><%= "Approved applications will be displayed here" unless @applications.select { |e| e.accepted? && Date.today < e.project.end_date }.first %></em></p>
        <h4>Closed</h4>
        <% @applications.select { |e| e.declined? || Date.today >= e.project.end_date }.each do |application| %>
          <div style="display: flex; align-items: center; margin: 4px;">
            <% if current_user.organization? %>
              <p><%= "#{application.created_at.strftime("%m/%d/%Y")} / #{application.user.first_name} #{application.user.last_name} - #{application.project.title}" %> </p>
            <% else %>
              <p><%= "#{application.created_at.strftime("%m/%d/%Y")} - #{application.project.title}" %> </p>
            <% end %>
            <% if current_user.organization? %>
              <%= link_to "Leave a review", new_user_review_path(application.user), class: 'btn main-btn btn-review' %>
            <% else %>
              <%= link_to "Leave a review", new_project_review_path(application.project), class: 'btn main-btn btn-review' %>
            <% end %>
          </div>
        <% end %>
        <p><em><%= "Closed applications will be displayed here" unless @applications.select { |e| e.declined? || Date.today >= e.project.end_date }.first %></em></p>
      </div>
      <div class="projects">
        <h3>Projects</h3>
        <% @projects.reverse.each do |project| %>
          <div class="dashboard-card-project">
            <%= project.photos.attached? ? (cl_image_tag project.photos.first.key) : (image_tag "project_default_background.jpg") %>
            <div class="project-info">
              <div class="info-text">
                <h4><%= project.title %> </h4>
                <p><%= project.description %><p>
              </div>
              <div class="links">
                <%= link_to "See the Project", project_path(project)  %>
                <% if current_user.organization? %>
                  <%= link_to edit_project_path(project) do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                  <%= link_to project_path(project), method: :delete do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="container-sidebar">
    <div class="container-news dash-news">
      <h4>The Good Dev News</h4>
      <%= render "projects/news" %>
    </div>
    <div class="container-projects">
      <h4>Latest Projects</h4>
      <% @all_projects.reverse[0..2].each do |project| %>
        <div class="card-project">
          <div class="review-avatar">
          <% if project.organization.user.photo.attached? %>
            <%= cl_image_tag project.organization.user.photo.key %>
          <% else %>
            <%= image_tag "default-avt.png" %>
          <% end %>
            <p> <%= project.organization.name %> </p>
            <p> <%# reviewer.organization? ?  "Host" : "Volunteer" %> </p>
          </div>
          <div class="review-content">
            <p><em>"<%= project.description %>"</em></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
index.html.erb

app/views/users/show.html.erb
<% if @user.organization? %>
  <%= render 'organization' %>
  <% else %>
  <%= render 'volunteer' %>
<% end %>