config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'users#dashboard', as: :dashboard
  get '/developers', to: 'pages#developers', as: :developers
  resources :projects do
    resources :chatrooms, only: :create
    resources :applications, only: [:new, :create]
    resources :reviews, only: [:new, :create]
    member do
      post :favorite
      post :unfavorite
    end
    resources :favorites, only: [:create] do
      collection do
        delete '/', action: :destroy
      end
    end
  end

  resources :applications, only: [] do
    get '/assess', to: 'applications#assess'
    patch '/', to: 'applications#respond'
  end

  resources :users, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    get '/my_skills', to: 'users#my_skills', as: :my_skills
    resources :my_skills, only:[:create]
    get '/my_languages', to: 'users#my_languages', as: :my_languages
    resources :my_languages, only:[:create]
  end
  resources :organizations, only: [:new, :create]
  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "logo1.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <div class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%#= link_to "Messages", chatrooms_path, class: "nav-link" %>
            <div class="messages">
              <%= link_to "Messages", "#", class: "nav-link" %>
                <% if @unread_messages == 0 %>

                <% else %>
              <div class="notification-msg" >
                  <%= @unread_messages %>
                  <%#= @chatroom.recipient %>
              </div>
                <% end %>
                <%#= @unread_messages unless @unread_messages == 0 %>
            </div>
          </div>
          <div>
            <% @chatrooms.each do |chatroom|  %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <% if current_user.volunteer? %>
                  <%= link_to "#{chatroom.recipient.organization.name}", chatroom_path(chatroom), class: "dropdown-item"  %>
                <% else %>
                  <%= link_to "#{chatroom.user.first_name}", chatroom_path(chatroom), class: "dropdown-item"  %>
                <% end %>
              </div>
            <% end %>
          </div>
        </li>

        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
              <img style="cursor: pointer" class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src= <%= cl_image_path current_user.photo.key, class: 'avatar' %> />
            <% else %>
              <img style="cursor: pointer" class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src= <%= image_path("default-avt.png") %> />
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "border-btn" %>
          </li>
        <li class="nav-item dropdown">
          <span class="dropdown-toggle main-btn" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Join</span>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Join as Volunteer", new_user_registration_path(partial: :volunteer), class: "dropdown-item" %>
            <%= link_to "Join as Organization", new_user_registration_path(partial: :organization), class: "dropdown-item" %>
          </div>
        </li>

      <% end %>
    </ul>
  </div>
</div>