config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'users#dashboard', as: :dashboard
  get '/developers', to: 'pages#developers', as: :developers
  resources :projects do
    resources :chatrooms, only: :create
    resources :applications, only: [:new, :create]
    resources :reviews, only: [:new, :create]
    member do
      post :favorite
      post :unfavorite
    end
    resources :favorites, only: [:create] do
      collection do
        delete '/', action: :destroy
      end
    end
  end

  resources :applications, only: [] do
    get '/assess', to: 'applications#assess'
    patch '/', to: 'applications#respond'
  end

  resources :users, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    get '/my_skills', to: 'users#my_skills', as: :my_skills
    resources :my_skills, only:[:create]
    get '/my_languages', to: 'users#my_languages', as: :my_languages
    resources :my_languages, only:[:create]
  end
  resources :organizations, only: [:new, :create]
  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end
end

app/views/pages/developers.html.erb
<div class="container dev">
  <h1>The Good Developers</h1>
  <p>In only two weeks our developers created a fully functional application, lots of hard work involved and not enough sleep, we were only 3 so there was even more work for each one of us. When we look at the final result we can be proud of what we acomplished and obviously all the hard word has paid off. I want to thank my partners for they're great work and commitment. To Emma and Oz, I'm sure your future in web development will be nothing but brilliant, <br><em>Love, Natalia.</em></p>
  <div class="cards d-flex justify-content-center">
    <div class="card-dev">
      <%= image_tag "https://kitt.lewagon.com/placeholder/users/Emmacard", class: "avatar-dev", alt: "avatar-large" %>
      <h4>Emma Cardon</h4>
      <p>Full Stack Developer</p>
      <hr>
      <div class="d-flex justify-content-center">
        <a href="https://github.com/Emmacard"><i class="fab fa-github"></i></a>
        <a href="https://www.linkedin.com/in/emma-cardon-45461066/"><i class="fab fa-linkedin-in"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>

    </div>
    <div class="card-dev">
      <%= image_tag "https://kitt.lewagon.com/placeholder/users/OzgurFiratSayin", class: "avatar-dev", alt: "avatar-large" %>
      <h4>Ozgur Firat Sayin</h4>
      <p>Full Stack Developer</p>
      <hr>
      <div class="d-flex justify-content-center">
        <a href="https://github.com/OzgurFiratSayin"><i class="fab fa-github"></i></a>
        <a href="https://www.linkedin.com/in/ozgur-firat-sayin-2b020b19/"><i class="fab fa-linkedin-in"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>

    </div>
    <div class="card-dev">
      <%= image_tag "https://kitt.lewagon.com/placeholder/users/nataliarossini", class: "avatar-dev", alt: "avatar-large" %>
      <h4>Natalia Rossini </h4>
      <p>Full Stack Developer</p>
      <hr>
      <div class="d-flex justify-content-center">
        <a href="https://github.com/nataliarossini"><i class="fab fa-github"></i></a>
        <a href="https://www.linkedin.com/in/natalia-rossini-727338116/"><i class="fab fa-linkedin-in"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-container">

  <div class="banner" >
    <div>
      <h1>Share your skills, <br> help people,<br> be a volunteer.</h1>
      <div class="banner-btns">
        <%= link_to 'See Projects', projects_path, class: 'main-btn' %>
        <a href="#about" class="border-btn">Learn More</a>
      </div>
    </div>
      <%= image_tag 'banner.svg' %>
  </div>

  <div class="sub-banner" style="background-color: white;">
    <div class="home-margin">
      <%# <div class="d-flex"> %>
        <%= image_tag 'worldmap.svg', class: 'img-home' %>
        <div class="sub-wrap">
          <h2 id="about">About us</h2>
          <p>We want to connect IT professionals and institutions who are willing to make a lasting change around the world.<br> Together we can make a difference.</p>
        </div>
      <%# </div> %>
    </div>
  </div>
  <div class="home-margin">
    <div class="container-home" style="background: url(<%= image_url('') %>) no-repeat right; background-size: 30%; " >
      <h2>How it works</h2>
      <div class="container-howitworks">
        <p>If you are a IT professional you can apply to work as a volunteer. We provide a range of intitutions willing to host you in exchange of your services. </p>
        <div class="capsule">
          <div id="center-image"> <%= image_tag 'img1.svg' %>
            <div class="step" id="step1"> <h1> 1 </h1> <p>Join our community</p> </div>
            <div class="step" id="step2"> <h1> 2 </h1> <p>Apply to work on a project</p></div>
            <div class="step" id="step3"> <h1> 3 </h1> <p>Wait for your application approval</p> </div>
            <div class="step" id="step4"> <h1> 4 </h1> <p>Gain experience while working in meaningful projects!</p> </div>
          </div>
        </div>
      </div>
      <div class="container-howitworks">
        <p>If you are a charity institution or a business aiming to work on along with high skilled IT professionals, The Good Dev got your back! You won’t have to worry about your bugdet, all you have to do is to host our amazing professionals who’s willing to help your cause and the community.</p>
        <div class="capsule">
          <div id="center-image"> <%= image_tag 'img2.svg' %>
            <div class="step" id="step1"> <h1> 1 </h1> <p>Register for free</p> </div>
            <div class="step" id="step2"> <h1> 2 </h1> <p>Share your project with our community</p></div>
            <div class="step" id="step3"> <h1> 3 </h1> <p>Connect with the professionals you need</p> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="sub-banner-sml" style="background-color: rgba(170, 216, 211, 0.3);">
    <div class="home-margin">
      <div>
        <h2>Post your project and find the volunteers you need</h2>
        <%= link_to "Post a project", new_project_path, class: "main-btn" %>
      </div>
    </div>
  </div>

  <div class="recent-posted">
      <h3>Recently posted</h3>
      <div class="container-cards">
        <% @projects.reverse.first(3).each do |project| %>
          <%= link_to project_path(project) do %>
            <% if project.photos.attached? %>
              <% photo_source = cl_image_path project.photos.first.key %>
            <% else %>
              <% photo_source = image_path("project_default_background.jpg") %>
            <% end %>
            <div class="card-project" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0, 0.7)), url(<%= photo_source %>);">
              <div class="cell">
                <p><i class="fas fa-map-pin"></i> <%= project.location %> </p>
              </div>
              <div class="cell">
                <h4> <%= project.title %> </h4>
                <p> <%= project.description %> <p>
              </div>
            </div>
          <% end %>
        <% end %>
        <div>
        <%= link_to 'See more', projects_path, class: "btn-filter" %>
        </div>
      </div>
  </div>
  <div id='pre-footer' class="sub-banner" style="background-color: white;">
    <div class="home-margin">
      <%= image_tag 'sub-banner2.svg' %>
      <div class="sub-wrap">
        <h2>Conversations today could lead<br> to opportunity tomorrow</h2>
        <p>Sending messages to people is a great way to build relationships as you take the next step in your career or projects</p>
      </div>
    </div>
  </div>



  <footer>
    <div class="footer-wrap">
      <%= image_tag "logo1.svg" %>
      <div class="footer-links">
        <div>
          <h3>General</h3>
          <li><a href="#">Sign Up</a></li>
          <li><a href="#">Help Center</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Press</a></li>
          <li><a href="#">Blog</a></li>
          <li><a href="#">Careers</a></li>
          <%= link_to "Developers", developers_path  %>
        </div>
        <div>
          <h3>Browse</h3>
          <li><a href="#">Projects</a></li>
          <li><a href="#">News</a></li>
          <li><a href="#">Fundraising</a></li>
          <li><a href="#">Services</a></li>
          <li><a href="#">Partners</a></li>
        </div>
        <div>
          <h3>Directories</h3>
          <li><a href="#">Projects</a></li>
          <li><a href="#">Members</a></li>
          <li><a href="#">Organizations</a></li>
          <li><a href="#">News Letter</a></li>
          <li><a href="#">Articles</a></li>
          <li><a href="#">Feedbacks</a></li>
          <li><a href="#">Schools</a></li>
        </div>
      </div>
    </div>
  </footer>
    <p class="credit"> <i class="fas fa-terminal"></i>   The-Good-Dev git:(team) ✗ Natalia, Ozgur & Emma  </p>
</div>