config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'users#dashboard', as: :dashboard
  get '/developers', to: 'pages#developers', as: :developers
  resources :projects do
    resources :chatrooms, only: :create
    resources :applications, only: [:new, :create]
    resources :reviews, only: [:new, :create]
    member do
      post :favorite
      post :unfavorite
    end
    resources :favorites, only: [:create] do
      collection do
        delete '/', action: :destroy
      end
    end
  end

  resources :applications, only: [] do
    get '/assess', to: 'applications#assess'
    patch '/', to: 'applications#respond'
  end

  resources :users, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    get '/my_skills', to: 'users#my_skills', as: :my_skills
    resources :my_skills, only:[:create]
    get '/my_languages', to: 'users#my_languages', as: :my_languages
    resources :my_languages, only:[:create]
  end
  resources :organizations, only: [:new, :create]
  resources :chatrooms, only: [:show] do
    resources :messages, only: :create
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organization
  has_many :applications
  validates :title, presence: true, length: { maximum: 20 }
  validates :description, presence: true, length: { maximum: 100 }
  validates :details, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  has_many_attached :photos
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  acts_as_favoritable
  include PgSearch::Model
  pg_search_scope :search_by_title_and_location,
    against: [ :title, :location ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  def index
    if params[:query].present?
      @projects = Project.search_by_title_and_location(params[:query])
      @reviews = Review.all
    else
      @projects = Project.all
      @reviews = Review.all
    end
  end

  def show
    @project = Project.find(params[:id])
    @chatroom = Chatroom.where(user: current_user, recipient: @project.organization.user).or(Chatroom.where(user: @project.organization.user, recipient: current_user)).first
    @markers = [{ lat: @project.latitude, lng: @project.longitude }]
    
    # @contact = Chatroom.create(name: 'Contact')
    # raise
    # if @contact.save
    #   redirect_to chatroom_path
    # else
    #   render :show
    # end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.organization = current_user.organization
    if @project.save
      MyBadge.create(user_id: current_user.id, badge_id: Badge.find_by(name: "Experienced Host").id).save if current_user.organization.projects.count == 10 # This line is for job-doer badge (see seed file)
      redirect_to @project
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to @project
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy if current_user.organization == @project.organization
    redirect_to projects_path
  end

  def favorite
    @project = Project.find(params[:id])
    current_user.favorite(@project)
    redirect_to projects_path

  end

  def unfavorite
    @project = Project.find(params[:id])
    current_user.unfavorite(@project)
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :details, :location, :start_date, :end_date, :remote, photos: [])
  end

end

app/views/projects/_form.html.erb
<%= simple_form_for (@project) do |f| %>
<%= f.error_notification %>
  <div class="form-inputs">
    <div class="division">
      <%= f.input :title, label: 'Project title' %>
      <%= f.input :location, label: 'Project location', input_html: { id: "user_address" } %>
    </div>
    <%= f.input :description, label: 'Project description' %>
    <%= f.input :details, label: 'Project details' %>
    <div class="division">
      <%= f.input :start_date, html5: true, label: 'Project start date' %>
      <%= f.input :end_date, html5: true, label: 'Project end date' %>
    </div>
    <%= f.input :remote, 
                :as => :radio_buttons, 
                :collection => [['Yes', true],['No', false]], 
                :label => "Remote" %>
    <%= f.input :photos, as: :file, input_html: { multiple: true, class: 'hidden', id: 'photo-input'}, label_html: { class: 'upload-file'}, label: 'Upload photos 📸'  %>
    <%= image_tag "", width: 300, class: "hidden prev-photo", id: "photo-preview" %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, current_page?(action: 'new') ? "Create Project" : "Edit Project", class: "main-btn" %>
  </div>
<% end %>

app/views/projects/_news.html.erb
<div class="card-news">
  <%= image_tag "women.jpg", alt: "alttext" %>
  <div class="news-content">
    <h4>Woman in Dev</h4>
    <p>Our initative to incentive women paticipation in technology and... <a href="#">Read</a></p>
  </div>
</div>
<div class="card-news">
  <%= image_tag "volunteers3.jpg", alt: "alttext" %>
  <div class="news-content">
    <h4>Education</h4>
    <p>Volunteers made programming more accessible by teach... <a href="#">Read</a></p>
  </div>
</div>
<div class="card-news">
  <%= image_tag "volunteers.png", alt: "alttext" %>
  <div class="news-content">
    <h4>Fundraising</h4>
    <p>The good dev had started a new fundraise project in order to provide... <a href="#">Read</a></p>
  </div>
</div>


<%# a group of 12 children%>

app/views/projects/edit.html.erb
<div class="page-form">
  <h2>Update the Project</h2>
  <div class="container">
      <%= render 'form' %>
  </div>
</div>

app/views/projects/index.html.erb
<div class= "container-main">
  <div class="holder">
    <h1> Projects Available </h1>
    <div class="filter-bar">
      <button class="btn-filter" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        Filter <i class="fas fa-chevron-down"></i>
      </button>
      <div class="collapse" id="collapseExample">
        <div class="card card-body">
          <%= form_tag projects_path, method: :get do %>
            <%= label_tag "Narrow your search" %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Search for a project or location"
            %>
            <%= submit_tag "Search", class: "btn-light-green mt-3" %>
          <% end %>


          <%#= simple_form_for :project, url: projects_path, method: :get do |f| %>
                <%#= f.input :query, label: "Narrow your search"%>
                <%#= f.button :submit, "Search" %>
          <%# end %>
        </div>
      </div>
    </div>
    <div class="container-cards">
      <% @projects.each do |project| %>

        <% if project.photos.attached? %>
          <% photo_source = cl_image_path project.photos.first.key %>
        <% else %>
          <% photo_source = image_path("project_default_background.jpg") %>
        <% end %>
        <div class="wrap-card">
          <%= link_to project_path(project), :class => "card-project",
                                             :style => "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(#{photo_source});" do %>

            <div class="cell">
              <p> <i class="fas fa-map-pin"></i> <%= project.location %> </p>
            </div>
            <div class="cell">
              <h3> <%= project.title %> </h3>
              <p> <%= project.description %> <p>
            </div>

          <% end %>

            <% if user_signed_in? %>
              <% if current_user.favorited?(project) %>
                <%= link_to project_favorites_path(project.id), remote: true, method: :delete do %>
                  <i class="fas fa-bookmark add"></i>
                <% end %>
              <% else %>
                <%= link_to project_favorites_path(project), remote: true, method: :post do %>
                  <i class="fas fa-bookmark"></i>
                <% end %>
              <% end %>
            <% end %>

        </div>
      <% end %>
    </div>
  </div>
  <div class="container-sidebar">
    <div class="container-news">
      <h4>The Good Dev News</h4>
      <%= render 'news' %>
    </div>
    <div class="container-reviews">
      <h4>Members Feedback</h4>
      <% @reviews.reverse[0..2].each do |review| %>
        <div class="card-review">
          <div class="review-avatar">
          <% reviewer = User.find(review.author_id) %>
            <% if reviewer.photo.attached? %>
              <%= cl_image_tag reviewer.photo.key, class: 'avatar' %>
            <% else %>
              <%= image_tag "default-avt.png" %>
            <% end %>
              <p> <%= reviewer.organization? ?  reviewer.organization.name : "#{reviewer.first_name.capitalize} #{reviewer.last_name.capitalize}" %> </p>
              <p> <%# reviewer.organization? ?  "Host" : "Volunteer" %> </p>
          </div>
          <div class="review-content">
            <p><em>"<%= review.content.truncate(80) %>"</em></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="page-form">
  <h2>Create a New Project</h2>
  <div class="container">
      <%= render 'form' %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="show-container">
  <div class="proj-info">
    <% if user_signed_in? %>
      <% if current_user.favorited?(@project) %>
        <%= link_to project_favorites_path(@project.id), method: :delete do %>
          <i class="fas fa-bookmark add"></i>
        <% end %>
      <% else %>
        <%= link_to project_favorites_path(@project), method: :post do %>
          <i class="fas fa-bookmark"></i>
        <% end %>
      <% end %>
    <% end %>
    <h2><%= @project.title %></h2>
    <hr>
    <h3>How you can help</h3>
    <p><%= @project.details %></p>
    <div>
      <h3>Location</h3>
    </div>
    <p><%= @project.location %></p>
    <div class="dates">
      <div>
        <h4>Start date</h4> <p><%= @project.start_date %></p>
      </div>
      <div>
        <h4>End date</h4> <p><%= @project.end_date %></p>
      </div>
    </div>
    <div class="proj-org">
      <div class= "org-info">
        <div class="line">
          <h3>About <%= link_to "#{@project.organization.name}", user_path(@project.organization.user) %></h3>
          <% if current_user && @project.organization.user != current_user %>
            <% if @chatroom %>
              <%= link_to chatroom_path(@chatroom) do %>
                <i class="fas fa-comments"></i>
              <% end %>
            <% else %>
              <%= link_to project_chatrooms_path(@project), method: :post do %>
                <i class="fas fa-comments"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <p><%= @project.organization.user.description %></p>
      </div>
      <div class="pict-org">
        <% if @project.organization.user.photo.attached? %>
          <%= cl_image_tag @project.organization.user.photo.key %>
        <% else %>
          <%= image_tag "default-avt.png" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card-map-column">
    <div class="proj-card">
      <div class="proj-photo">
        <% if @project.photos.length == 1  %>
          <%= cl_image_tag @project.photos.first.key %>
        <% elsif @project.photos.length > 1 %>
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            </ol>
            <div class="carousel-inner">
              <% @project.photos.each do |photo| %>
              <div class="carousel-item <%= 'active' if photo == @project.photos[0] %>">
                <%= cl_image_tag photo.key, class: "d-block w-100" %>
              </div>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        <% else %>
          <%= image_tag "default-project-photo-unsplash.jpg" %>
        <% end %>
      </div>
      <div class="buttons">
        <% if @project.organization.user_id == current_user&.id %>
          <div>
            <%= link_to "Update the Project", edit_project_path(@project), class: "btn btn-light-green" %>
            <%= link_to "Delete this Project", project_path(@project), method: :delete, class: "btn btn-coral" %>
          </div>
        <% elsif current_user%>
          <% if current_user.applications.select { |a| a.project_id == @project.id }.length == 0 %>
            <%= link_to "Apply", new_project_application_path(@project), class: 'btn btn-light-green' %>
          <% else %>
            <% if Date.today >= @project.end_date %>
              <%= link_to "Leave a review", new_project_review_path(@project), class: 'btn btn-light-green' %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div id="map" class="map-style"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <%# link_to "Back to Projects", projects_path, class: 'back-btn' %>
</div>